"""Add Phase 3 schema

Revision ID: 43651a96474d
Revises: fa3ca63bb938
Create Date: 2026-06-16 11:17:59.365016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43651a96474d'
down_revision: Union[str, None] = 'fa3ca63bb938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('confidence_score', sa.Integer(), server_default='50', nullable=False))
    op.add_column('properties', sa.Column('status', sa.String(length=30), server_default='active', nullable=False))
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'confidence_score')
    # ### end Alembic commands ###
